pluginVersion=3.0.0

# https://www.jetbrains.com/intellij-repository/snapshots
riderSdkVersion=2025.2
untilBuildVersion=253

buildConfiguration=Debug

riderPluginId=com.jetbrains.rider.plugins.meadow
dotNetPluginId=MeadowPlugin

kotlin.stdlib.default.dependency=false
org.jetbrains.intellij.platform.buildFeature.useBinaryReleases=false
