//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace MeadowPlugin.Model
{
  
  
  /// <summary>
  /// <p>Generated from: MeadowPluginModel.kt:11</p>
  /// </summary>
  public class MeadowPluginModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<Unit, List<string>> GetSerialPorts => _GetSerialPorts;
    [NotNull] public IRdEndpoint<DebugServerInfo, Unit> StartDebugServer => _StartDebugServer;
    [NotNull] public IRdEndpoint<string, Unit> Terminate => _Terminate;
    
    //private fields
    [NotNull] private readonly RdCall<Unit, List<string>> _GetSerialPorts;
    [NotNull] private readonly RdCall<DebugServerInfo, Unit> _StartDebugServer;
    [NotNull] private readonly RdCall<string, Unit> _Terminate;
    
    //primary constructor
    private MeadowPluginModel(
      [NotNull] RdCall<Unit, List<string>> getSerialPorts,
      [NotNull] RdCall<DebugServerInfo, Unit> startDebugServer,
      [NotNull] RdCall<string, Unit> terminate
    )
    {
      if (getSerialPorts == null) throw new ArgumentNullException("getSerialPorts");
      if (startDebugServer == null) throw new ArgumentNullException("startDebugServer");
      if (terminate == null) throw new ArgumentNullException("terminate");
      
      _GetSerialPorts = getSerialPorts;
      _StartDebugServer = startDebugServer;
      _Terminate = terminate;
      _GetSerialPorts.Async = true;
      _StartDebugServer.Async = true;
      _Terminate.Async = true;
      BindableChildren.Add(new KeyValuePair<string, object>("getSerialPorts", _GetSerialPorts));
      BindableChildren.Add(new KeyValuePair<string, object>("startDebugServer", _StartDebugServer));
      BindableChildren.Add(new KeyValuePair<string, object>("terminate", _Terminate));
    }
    //secondary constructor
    internal MeadowPluginModel (
    ) : this (
      new RdCall<Unit, List<string>>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, ReadStringList, WriteStringList),
      new RdCall<DebugServerInfo, Unit>(DebugServerInfo.Read, DebugServerInfo.Write, JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdCall<string, Unit>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    protected override long SerializationHash => -2257001314127068400L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      serializers.Register(MeadowDeploymentArgs.Read, MeadowDeploymentArgs.Write);
      serializers.Register(MeadowDeploymentResult.Read, MeadowDeploymentResult.Write);
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("MeadowPluginModel (");
      using (printer.IndentCookie()) {
        printer.Print("getSerialPorts = "); _GetSerialPorts.PrintEx(printer); printer.Println();
        printer.Print("startDebugServer = "); _StartDebugServer.PrintEx(printer); printer.Println();
        printer.Print("terminate = "); _Terminate.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionMeadowPluginModelEx
   {
    public static MeadowPluginModel GetMeadowPluginModel(this JetBrains.Rider.Model.Solution solution)
    {
      return solution.GetOrCreateExtension("meadowPluginModel", () => new MeadowPluginModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MeadowPluginModel.kt:22</p>
  /// </summary>
  public sealed class DebugServerInfo : IPrintable, IEquatable<DebugServerInfo>
  {
    //fields
    //public fields
    [NotNull] public string SerialPort {get; private set;}
    public int DebugPort {get; private set;}
    
    //private fields
    //primary constructor
    public DebugServerInfo(
      [NotNull] string serialPort,
      int debugPort
    )
    {
      if (serialPort == null) throw new ArgumentNullException("serialPort");
      
      SerialPort = serialPort;
      DebugPort = debugPort;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string serialPort, out int debugPort)
    {
      serialPort = SerialPort;
      debugPort = DebugPort;
    }
    //statics
    
    public static CtxReadDelegate<DebugServerInfo> Read = (ctx, reader) => 
    {
      var serialPort = reader.ReadString();
      var debugPort = reader.ReadInt();
      var _result = new DebugServerInfo(serialPort, debugPort);
      return _result;
    };
    
    public static CtxWriteDelegate<DebugServerInfo> Write = (ctx, writer, value) => 
    {
      writer.Write(value.SerialPort);
      writer.Write(value.DebugPort);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((DebugServerInfo) obj);
    }
    public bool Equals(DebugServerInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return SerialPort == other.SerialPort && DebugPort == other.DebugPort;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + SerialPort.GetHashCode();
        hash = hash * 31 + DebugPort.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("DebugServerInfo (");
      using (printer.IndentCookie()) {
        printer.Print("serialPort = "); SerialPort.PrintEx(printer); printer.Println();
        printer.Print("debugPort = "); DebugPort.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MeadowPluginModel.kt:13</p>
  /// </summary>
  public sealed class MeadowDeploymentArgs : JetBrains.Rider.Model.DeploymentArgsBase
  {
    //fields
    //public fields
    [NotNull] public string SerialPort {get; private set;}
    [NotNull] public string AppPath {get; private set;}
    public bool Debug {get; private set;}
    
    //private fields
    //primary constructor
    public MeadowDeploymentArgs(
      [NotNull] string serialPort,
      [NotNull] string appPath,
      bool debug,
      [NotNull] JetBrains.Rider.Model.RunnableProjectKind projectKind,
      [NotNull] string projectFilePath
    ) : base (
      projectKind,
      projectFilePath
     ) 
    {
      if (serialPort == null) throw new ArgumentNullException("serialPort");
      if (appPath == null) throw new ArgumentNullException("appPath");
      
      SerialPort = serialPort;
      AppPath = appPath;
      Debug = debug;
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<MeadowDeploymentArgs> Read = (ctx, reader) => 
    {
      var projectKind = JetBrains.Rider.Model.RunnableProjectKind.Read(ctx, reader);
      var projectFilePath = reader.ReadString();
      var serialPort = reader.ReadString();
      var appPath = reader.ReadString();
      var debug = reader.ReadBool();
      var _result = new MeadowDeploymentArgs(serialPort, appPath, debug, projectKind, projectFilePath);
      return _result;
    };
    
    public static new CtxWriteDelegate<MeadowDeploymentArgs> Write = (ctx, writer, value) => 
    {
      JetBrains.Rider.Model.RunnableProjectKind.Write(ctx, writer, value.ProjectKind);
      writer.Write(value.ProjectFilePath);
      writer.Write(value.SerialPort);
      writer.Write(value.AppPath);
      writer.Write(value.Debug);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MeadowDeploymentArgs) obj);
    }
    public bool Equals(MeadowDeploymentArgs other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return SerialPort == other.SerialPort && AppPath == other.AppPath && Debug == other.Debug && Equals(ProjectKind, other.ProjectKind) && ProjectFilePath == other.ProjectFilePath;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + SerialPort.GetHashCode();
        hash = hash * 31 + AppPath.GetHashCode();
        hash = hash * 31 + Debug.GetHashCode();
        hash = hash * 31 + ProjectKind.GetHashCode();
        hash = hash * 31 + ProjectFilePath.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MeadowDeploymentArgs (");
      using (printer.IndentCookie()) {
        printer.Print("serialPort = "); SerialPort.PrintEx(printer); printer.Println();
        printer.Print("appPath = "); AppPath.PrintEx(printer); printer.Println();
        printer.Print("debug = "); Debug.PrintEx(printer); printer.Println();
        printer.Print("projectKind = "); ProjectKind.PrintEx(printer); printer.Println();
        printer.Print("projectFilePath = "); ProjectFilePath.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MeadowPluginModel.kt:19</p>
  /// </summary>
  public sealed class MeadowDeploymentResult : JetBrains.Rider.Model.DeploymentResultBase
  {
    //fields
    //public fields
    
    //private fields
    //primary constructor
    public MeadowDeploymentResult(
      JetBrains.Rider.Model.DeploymentResultStatus status
    ) : base (
      status
     ) 
    {
    }
    //secondary constructor
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<MeadowDeploymentResult> Read = (ctx, reader) => 
    {
      var status = (JetBrains.Rider.Model.DeploymentResultStatus)reader.ReadInt();
      var _result = new MeadowDeploymentResult(status);
      return _result;
    };
    
    public static new CtxWriteDelegate<MeadowDeploymentResult> Write = (ctx, writer, value) => 
    {
      writer.Write((int)value.Status);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MeadowDeploymentResult) obj);
    }
    public bool Equals(MeadowDeploymentResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Status == other.Status;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + (int) Status;
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MeadowDeploymentResult (");
      using (printer.IndentCookie()) {
        printer.Print("status = "); Status.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
